#### Numpy
NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and 2D Arrays, along with a collection of mathematical functions to operate on these data structures.

```pip install numpy``` Just Write this in jupiter notebook and run it

In [3]:
import numpy as rajatNumpy

# Create a 1-D array using numpy
array1 = rajatNumpy.array([1, 2, 3, 4, 5])
print(array1)  # [1 2 3 4 5]
print(type(array1))  # <class 'numpy.ndarray'>
print(array1.shape)  # (5,) - The array has 5 elements (in one dimension)


[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [5]:
# Create a 2-D array using numpy
array2 = rajatNumpy.array([[1, 2, 3,4,5], [4, 5, 6,7,8], [7, 8, 9,10,11]])
print(array2)
# [[ 1  2  3  4  5]
#  [ 4  5  6  7  8]
#  [ 7  8  9 10 11]]
print(array2.shape)  # (3, 5) - The array has 3 rows and 5 columns

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 7  8  9 10 11]]
(3, 5)


In [9]:
# We can convert a 2-D array to 1-D array using flatten() method
array3 = array2.flatten()
print(array3)  # [ 1  2  3  4  5  4  5  6  7  8  7  8  9 10 11]
print(array3.shape) # (15,) - The array has 15 elements (in one dimension)

# We can convert a 1-D array to 2-D array using reshape() method
array4 = array3.reshape(5, 3)
print(array4)
# [[ 1  2  3]
#  [ 4  5  4]
#  [ 5  6  7]
#  [ 8  7  8]
#  [ 9 10 11]]

[ 1  2  3  4  5  4  5  6  7  8  7  8  9 10 11]
(15,)
[[ 1  2  3]
 [ 4  5  4]
 [ 5  6  7]
 [ 8  7  8]
 [ 9 10 11]]


In [11]:
# Another way to create Array 
array5 = rajatNumpy.arange(1, 10) # Create an array with elements from 1 to 9
print(array5)  # [1 2 3 4 5 6 7 8 9]

# Matrix of only 1's
rajatNumpy.ones((3,4))
# array([[1., 1., 1., 1.],
#        [1., 1., 1., 1.],
#        [1., 1., 1., 1.]])

# Identity Matrix - Matrix with 1's in diagonal and 0's elsewhere
rajatNumpy.eye(3)


[1 2 3 4 5 6 7 8 9]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Frequently used Attributes on numpy arrays
arr = rajatNumpy.array([[1, 2, 3], [4, 5, 6]])

print("Number of dimensions:", arr.ndim)  # 2: 2-dimensional array
print("Size (number of elements):", arr.size)  # 6: total elements in the array
print("Data type of elements:", arr.dtype)  # int32 or int64, depending on platform
print("Item size (in bytes):", arr.itemsize)  # Size of each element in bytes (e.g., 4 or 8)

Number of dimensions: 2
Size (number of elements): 9
Data type of elements: <U21
Item size (in bytes): 84


### Element-Wise Operations

#### Vectorised Operations on Numpy

In [17]:
arr1=rajatNumpy.array([1,2,3,4,5])
arr2=rajatNumpy.array([10,20,30,40,50])

# Element-wise operations
# Addition
print("Addition:", arr1+arr2)

# Substraction
print("Substraction:", arr1-arr2)

# Multiplication
print("Multiplication:", arr1 * arr2)

# Division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


#### Universal Function

In [21]:
arr=rajatNumpy.array([2,3,4,5,9])

# SquareRoot
print(rajatNumpy.sqrt(arr))

# Exponential
print(rajatNumpy.exp(arr))

# Sine
print(rajatNumpy.sin(arr))

# NaturalLog
print(rajatNumpy.log(arr))

[1.41421356 1.73205081 2.         2.23606798 3.        ]
[7.38905610e+00 2.00855369e+01 5.45981500e+01 1.48413159e+02
 8.10308393e+03]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427  0.41211849]
[0.69314718 1.09861229 1.38629436 1.60943791 2.19722458]


### Array Slicing and Operations

In [26]:
arr=rajatNumpy.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
print(arr[1:,1:3]) # [[ 6  7] [10 11]] - Slicing rows 1 to end and columns 1 to 3
print(arr[0][0]) # 1 - Element at 0th row and 0th column
print(arr[0:2,2:]) # [[3 4] [7 8]] - Slicing rows 0 to 2 and columns 2 to end
arr[0,0]=100 # Modify the element at 0th row and 0th column

[[ 6  7]
 [10 11]]
1
[[3 4]
 [7 8]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


## Practical Implementation 🔥

#### - Statstical Concepts : Normalization (Brief : to have a mean of 0 and standard deviation of 1)

In [ ]:
data = rajatNumpy.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = rajatNumpy.mean(data)
print("Mean:", mean)

# Median
median = rajatNumpy.median(data)
print("Median:", median)

# Standard deviation
std_dev = rajatNumpy.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = rajatNumpy.var(data)
print("Variance:", variance)


#### - Logical Operation

In [31]:
## Logical operation
data=rajatNumpy.array([1,2,3,4,5,6,7,8,9,10])
data>5 # array([False, False, False, False, False,  True,  True,  True,  True, True])
data[data>5] # array([ 6,  7,  8,  9, 10])
# Note : 'and' wont work instead Logical '&' will be used
data[(data>=5) & (data<=8)] # array([5, 6, 7, 8])



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])